# Generated by Django 4.2.1 on 2025-05-15 17:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('GOSPEL', 'Gospel'), ('ROCK', 'Rock'), ('POP', 'Pop'), ('JAZZ', 'Jazz'), ('CLASSICAL', 'Classical'), ('HIPHOP', 'Hip Hop'), ('ELECTRONIC', 'Electronic'), ('OTHER', 'Other')], max_length=100)),
                ('instrument', models.CharField(choices=[('GUITAR', 'Guitar'), ('PIANO', 'Piano'), ('DRUMS', 'Drums'), ('BASS', 'Bass'), ('VIOLIN', 'Violin'), ('VOICE', 'Voice'), ('OTHER', 'Other')], max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('availability', models.BooleanField(default=True)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('available_to', models.DateField(blank=True, null=True)),
                ('bio', models.TextField()),
                ('sample_work', models.URLField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('website', models.URLField(blank=True, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='musician_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
